pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet --info
  displayName: "dotnet info"
- script: dotnet restore
  displayName: "dotnet restore"
- script: dotnet build -c Release
  displayName: "dotnet build"
